/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JCheckBox;
import logica.LogicaReloj;
import logica.LogicaTareasPrioritarias;

/**
 *
 * @author caroR
 */
public class VentanaPrincipal extends javax.swing.JFrame {
       
   // para mover la ventana  
    private int mouseX;
    private int mouseY;
     
    
    //instancio la clase logica del reloj
    LogicaReloj temporizador;
    
    //instancio la clase Logica tareas
    LogicaTareasPrioritarias tareas;
    

    
    

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        jPanelPrioridades.setOpaque(false);
        jPanelPrioridades.setBackground(new java.awt.Color(0,0,0,0));
        
        //instanciamos la clase que contiene la logica del Cronometro y ademas instanciamos al JDialog
       temporizador = new LogicaReloj(jLReloj, this);
       
       //logica de el panel de tareas 
       tareas = new LogicaTareasPrioritarias(jTextTarea, new JCheckBox[]{jCheckBoxTarea1,jCheckBoxTarea2, jCheckBoxTarea3 , jCheckBoxTarea4}, this);
      
       this.setLocationRelativeTo(null); //centra la ventana en la pantalla
       
      

    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jBTrabajo = new javax.swing.JButton();
        jBDescansoLargo = new javax.swing.JButton();
        jBDescansoCorto = new javax.swing.JButton();
        jLReloj = new javax.swing.JLabel();
        jBEmpezar = new javax.swing.JButton();
        jBReiniciar = new javax.swing.JButton();
        JpanelLogo = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jPanelPrioridades = new javax.swing.JPanel();
        jLabelTituloPrioridades = new javax.swing.JLabel();
        jTextTarea = new javax.swing.JTextField();
        jBAgregarTarea = new javax.swing.JButton();
        jCheckBoxTarea1 = new javax.swing.JCheckBox();
        jCheckBoxTarea2 = new javax.swing.JCheckBox();
        jCheckBoxTarea3 = new javax.swing.JCheckBox();
        jCheckBoxTarea4 = new javax.swing.JCheckBox();
        jPanelSalir = new javax.swing.JPanel();
        jLabelSalir = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POMOGREEN");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backgroundMouseDragged(evt);
            }
        });
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backgroundMousePressed(evt);
            }
        });
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBTrabajo.setBackground(java.awt.SystemColor.inactiveCaption);
        jBTrabajo.setFont(new java.awt.Font("Roboto SemiCondensed Black", 0, 36)); // NOI18N
        jBTrabajo.setForeground(new java.awt.Color(255, 255, 255));
        jBTrabajo.setText("ENFOCATE");
        jBTrabajo.setBorder(null);
        jBTrabajo.setContentAreaFilled(false);
        jBTrabajo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBTrabajo.setFocusPainted(false);
        jBTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTrabajoActionPerformed(evt);
            }
        });
        background.add(jBTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 180, 50));

        jBDescansoLargo.setBackground(new java.awt.Color(204, 204, 204));
        jBDescansoLargo.setFont(new java.awt.Font("Roboto SemiCondensed Black", 0, 36)); // NOI18N
        jBDescansoLargo.setForeground(new java.awt.Color(255, 255, 255));
        jBDescansoLargo.setText("DESCANSO");
        jBDescansoLargo.setContentAreaFilled(false);
        jBDescansoLargo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBDescansoLargo.setMaximumSize(new java.awt.Dimension(102, 29));
        jBDescansoLargo.setMinimumSize(new java.awt.Dimension(102, 29));
        jBDescansoLargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDescansoLargoActionPerformed(evt);
            }
        });
        background.add(jBDescansoLargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 290, 50));

        jBDescansoCorto.setBackground(new java.awt.Color(204, 204, 204));
        jBDescansoCorto.setFont(new java.awt.Font("Roboto SemiCondensed Black", 0, 36)); // NOI18N
        jBDescansoCorto.setForeground(new java.awt.Color(255, 255, 255));
        jBDescansoCorto.setText("RESPIRA");
        jBDescansoCorto.setContentAreaFilled(false);
        jBDescansoCorto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBDescansoCorto.setMaximumSize(new java.awt.Dimension(102, 29));
        jBDescansoCorto.setMinimumSize(new java.awt.Dimension(102, 29));
        jBDescansoCorto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDescansoCortoActionPerformed(evt);
            }
        });
        background.add(jBDescansoCorto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 240, 50));

        jLReloj.setFont(new java.awt.Font("Roboto SemiCondensed Medium", 1, 75)); // NOI18N
        jLReloj.setForeground(new java.awt.Color(255, 255, 255));
        jLReloj.setText("25:00");
        background.add(jLReloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 220, 110));

        jBEmpezar.setBackground(new java.awt.Color(0, 51, 51));
        jBEmpezar.setFont(new java.awt.Font("Roboto SemiCondensed Black", 0, 24)); // NOI18N
        jBEmpezar.setForeground(new java.awt.Color(255, 255, 255));
        jBEmpezar.setText("EMPEZAR");
        jBEmpezar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jBEmpezar.setContentAreaFilled(false);
        jBEmpezar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEmpezarActionPerformed(evt);
            }
        });
        background.add(jBEmpezar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 120, 40));

        jBReiniciar.setBackground(new java.awt.Color(204, 204, 204));
        jBReiniciar.setFont(new java.awt.Font("Roboto SemiCondensed Black", 0, 24)); // NOI18N
        jBReiniciar.setForeground(new java.awt.Color(255, 255, 255));
        jBReiniciar.setText("REINICIAR");
        jBReiniciar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jBReiniciar.setContentAreaFilled(false);
        jBReiniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReiniciarActionPerformed(evt);
            }
        });
        background.add(jBReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 140, 40));

        JpanelLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pomogreen (2).png"))); // NOI18N
        jLabelLogo.setText("imagenLogo");
        jLabelLogo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelLogo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        JpanelLogo.add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 90));

        background.add(JpanelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 80));

        jPanelPrioridades.setName("PRIORIDADES"); // NOI18N
        jPanelPrioridades.setOpaque(false);
        jPanelPrioridades.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTituloPrioridades.setFont(new java.awt.Font("Roboto SemiCondensed Black", 1, 18)); // NOI18N
        jLabelTituloPrioridades.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloPrioridades.setText("TAREAS PRIORITARIAS");
        jPanelPrioridades.add(jLabelTituloPrioridades, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, -1));

        jTextTarea.setBackground(new java.awt.Color(0, 0, 0));
        jTextTarea.setFont(new java.awt.Font("Roboto SemiCondensed Black", 0, 18)); // NOI18N
        jTextTarea.setForeground(new java.awt.Color(255, 255, 255));
        jTextTarea.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextTarea.setText("Añade tu tarea prioritaria aquí");
        jTextTarea.setAlignmentX(0.8F);
        jTextTarea.setAlignmentY(0.8F);
        jTextTarea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTextTarea.setMinimumSize(new java.awt.Dimension(100, 30));
        jTextTarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextTareaMousePressed(evt);
            }
        });
        jTextTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTareaActionPerformed(evt);
            }
        });
        jPanelPrioridades.add(jTextTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 680, 40));

        jBAgregarTarea.setBackground(new java.awt.Color(204, 204, 204));
        jBAgregarTarea.setFont(new java.awt.Font("Roboto SemiCondensed SemiBold", 0, 18)); // NOI18N
        jBAgregarTarea.setText("OK");
        jBAgregarTarea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBAgregarTarea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAgregarTarea.setOpaque(true);
        jBAgregarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarTareaActionPerformed(evt);
            }
        });
        jPanelPrioridades.add(jBAgregarTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 40, 40));

        jCheckBoxTarea1.setFont(new java.awt.Font("Roboto SemiCondensed Medium", 0, 24)); // NOI18N
        jCheckBoxTarea1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxTarea1.setText("Prioridad 1");
        jCheckBoxTarea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTarea1ActionPerformed(evt);
            }
        });
        jPanelPrioridades.add(jCheckBoxTarea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 340, 30));

        jCheckBoxTarea2.setFont(new java.awt.Font("Roboto SemiCondensed Medium", 0, 24)); // NOI18N
        jCheckBoxTarea2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxTarea2.setText("Prioridad 2");
        jCheckBoxTarea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTarea2ActionPerformed(evt);
            }
        });
        jPanelPrioridades.add(jCheckBoxTarea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 340, 30));

        jCheckBoxTarea3.setFont(new java.awt.Font("Roboto SemiCondensed Medium", 0, 24)); // NOI18N
        jCheckBoxTarea3.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxTarea3.setText("Prioridad 3");
        jCheckBoxTarea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTarea3ActionPerformed(evt);
            }
        });
        jPanelPrioridades.add(jCheckBoxTarea3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 260, 30));

        jCheckBoxTarea4.setFont(new java.awt.Font("Roboto SemiCondensed Medium", 0, 24)); // NOI18N
        jCheckBoxTarea4.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxTarea4.setText("Prioridad 4");
        jCheckBoxTarea4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTarea4ActionPerformed(evt);
            }
        });
        jPanelPrioridades.add(jCheckBoxTarea4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 260, 40));

        background.add(jPanelPrioridades, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 770, 200));

        jPanelSalir.setBackground(new java.awt.Color(204, 0, 0));
        jPanelSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSalirMouseClicked(evt);
            }
        });
        jPanelSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSalir.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 14)); // NOI18N
        jLabelSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSalir.setText("X");
        jLabelSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSalir.add(jLabelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        background.add(jPanelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 30, 30));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoLuzBlanca.png"))); // NOI18N
        jLabelFondo.setText("jLabelFondo");
        jLabelFondo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jLabelFondoAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        background.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 820, 630));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelFondoAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabelFondoAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelFondoAncestorMoved

    private void jBDescansoLargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDescansoLargoActionPerformed
        temporizador.descansoLargo();
    }//GEN-LAST:event_jBDescansoLargoActionPerformed

    private void jBEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEmpezarActionPerformed
        temporizador.iniciar();
        
    }//GEN-LAST:event_jBEmpezarActionPerformed

    private void jBAgregarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarTareaActionPerformed
        tareas.agregarTarea();
    }//GEN-LAST:event_jBAgregarTareaActionPerformed

    
    private void jTextTareaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextTareaMousePressed
        //EVENTO que hace que se borre el texto automaticamente al hacerle clic al jTextFile (Event -> Mouse -> mousePressed)
        if (jTextTarea.getText().equals("Añade tu tarea prioritaria aquí")) {
            jTextTarea.setText("");
}
    }//GEN-LAST:event_jTextTareaMousePressed

    private void jTextTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTareaActionPerformed

    private void jCheckBoxTarea4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTarea4ActionPerformed
        tareas.eliminarTareaMarcada();
    }//GEN-LAST:event_jCheckBoxTarea4ActionPerformed

    private void jBReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReiniciarActionPerformed
        //reiniciar temporizador
        temporizador.reinicio();
    }//GEN-LAST:event_jBReiniciarActionPerformed

    private void jBDescansoCortoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDescansoCortoActionPerformed
        //respira
        temporizador.descansoCorto();
    }//GEN-LAST:event_jBDescansoCortoActionPerformed

    private void jBTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTrabajoActionPerformed
        // concentracion
        temporizador.trabajo();
    }//GEN-LAST:event_jBTrabajoActionPerformed

    private void jCheckBoxTarea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTarea1ActionPerformed
        tareas.eliminarTareaMarcada();
    }//GEN-LAST:event_jCheckBoxTarea1ActionPerformed

    private void jCheckBoxTarea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTarea2ActionPerformed
        tareas.eliminarTareaMarcada();
    }//GEN-LAST:event_jCheckBoxTarea2ActionPerformed

    private void jCheckBoxTarea3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTarea3ActionPerformed
        tareas.eliminarTareaMarcada();
    }//GEN-LAST:event_jCheckBoxTarea3ActionPerformed

    private void jPanelSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jPanelSalirMouseClicked

    private void backgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMousePressed
        // evento que se usa para mover la pantalla         
        mouseX = evt.getXOnScreen();
        mouseY = evt.getYOnScreen();
    }//GEN-LAST:event_backgroundMousePressed

    private void backgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseDragged
        // Mover la ventana
        int desplazamientoX = evt.getXOnScreen() - mouseX;
        int desplazamientoY = evt.getYOnScreen() - mouseY;
        
        //mover la ventana a la nueva posicion
        this.setLocation(this.getX() + desplazamientoX, this.getY() + desplazamientoY);
        
        //Actualizar las posiciones bases del mouse
        mouseX = evt.getXOnScreen();
        mouseY = evt.getYOnScreen();        
    }//GEN-LAST:event_backgroundMouseDragged

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpanelLogo;
    private javax.swing.JPanel background;
    private javax.swing.JButton jBAgregarTarea;
    private javax.swing.JButton jBDescansoCorto;
    private javax.swing.JButton jBDescansoLargo;
    private javax.swing.JButton jBEmpezar;
    private javax.swing.JButton jBReiniciar;
    private javax.swing.JButton jBTrabajo;
    private javax.swing.JCheckBox jCheckBoxTarea1;
    private javax.swing.JCheckBox jCheckBoxTarea2;
    private javax.swing.JCheckBox jCheckBoxTarea3;
    private javax.swing.JCheckBox jCheckBoxTarea4;
    private javax.swing.JLabel jLReloj;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelSalir;
    private javax.swing.JLabel jLabelTituloPrioridades;
    private javax.swing.JPanel jPanelPrioridades;
    private javax.swing.JPanel jPanelSalir;
    private javax.swing.JTextField jTextTarea;
    // End of variables declaration//GEN-END:variables
}
