/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import datos.UsuarioDAO;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author caroR
 */
public class VentanaLogin extends javax.swing.JFrame {
        
    // para mover la ventana  
    private int mouseX;
    private int mouseY;
     

    /**
     * Creates new form VentanaLogin
     */
    public VentanaLogin() {
        initComponents();
       
        //para poner en el panel Login semitrasparente
        jPanelLogin.setBorder(new ui.RoundedBorder(20, new Color(200, 200, 200), 5));
        jPanelLogin.setBackground(new java.awt.Color(255, 255, 255, 180)); // blanco semitransparente
        jPanelLogin.setOpaque(true);
        
        //para ponre bordes redondos en el boton de ingresar
        jButtonIngresar.setBackground(new Color(78, 148, 79)); // verde Material Design
        jButtonIngresar.setBorder(new ui.RoundedBorder(20, new Color(76, 175, 80), 2)); // borde verde redondeado
        jButtonIngresar.setForeground(Color.WHITE); // texto blanco
        jButtonIngresar.setFocusPainted(false);
        jButtonIngresar.setContentAreaFilled(true);
        jButtonIngresar.setOpaque(true);
        
        //para ponre bordes redondos en el boton de registro
        jButtonRegistro.setBackground(new Color(78, 148, 79)); // verde Material Design
        jButtonRegistro.setBorder(new ui.RoundedBorder(20, new Color(76, 175, 80), 2)); // borde verde redondeado
        jButtonRegistro.setForeground(Color.WHITE); // texto blanco
        jButtonRegistro.setFocusPainted(false);
        jButtonRegistro.setContentAreaFilled(true);
        jButtonRegistro.setOpaque(true);
        
        
        // Inicializamos el combo con los tipos de usuario al crear la ventana
        jComboBoxTipoU.setModel(
            new javax.swing.DefaultComboBoxModel<>(new String[] { "Alumno", "Profesor", "Otro" }));
        
        this.setLocationRelativeTo(null); //centra la ventana en la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        BackGround = new javax.swing.JPanel();
        jPanelSalir = new javax.swing.JPanel();
        jLabelSalirX = new javax.swing.JLabel();
        jPanelLogin = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelContrasenia = new javax.swing.JLabel();
        jPasswordFieldContraseña = new javax.swing.JPasswordField();
        jComboBoxTipoU = new javax.swing.JComboBox<>();
        jLabelTipoUsurario = new javax.swing.JLabel();
        jButtonIngresar = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        jButtonRegistro = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(550, 450));
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSalir.setBackground(new java.awt.Color(204, 0, 0));
        jPanelSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSalirX.setBackground(new java.awt.Color(255, 0, 0));
        jLabelSalirX.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabelSalirX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSalirX.setText("X");
        jLabelSalirX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelSalirXMousePressed(evt);
            }
        });
        jPanelSalir.add(jLabelSalirX, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        BackGround.add(jPanelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 30, 30));

        jPanelLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelLogin.setToolTipText("");
        jPanelLogin.setOpaque(false);
        jPanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelUsuario.setFont(new java.awt.Font("Roboto SemiCondensed SemiBold", 1, 18)); // NOI18N
        jLabelUsuario.setText("USUARIO");
        jPanelLogin.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 90, 30));

        jTextFieldUsuario.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jTextFieldUsuario.setBorder(null);
        jTextFieldUsuario.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        jPanelLogin.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 290, 30));

        jLabelContrasenia.setFont(new java.awt.Font("Roboto SemiCondensed SemiBold", 1, 18)); // NOI18N
        jLabelContrasenia.setText("CONTRASEÑA");
        jPanelLogin.add(jLabelContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 130, 30));

        jPasswordFieldContraseña.setText("Ingresa Contraseña");
        jPasswordFieldContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldContraseñaFocusLost(evt);
            }
        });
        jPasswordFieldContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldContraseñaActionPerformed(evt);
            }
        });
        jPanelLogin.add(jPasswordFieldContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 290, 30));

        jComboBoxTipoU.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jComboBoxTipoU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxTipoU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoUActionPerformed(evt);
            }
        });
        jPanelLogin.add(jComboBoxTipoU, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 290, 30));

        jLabelTipoUsurario.setFont(new java.awt.Font("Roboto SemiCondensed SemiBold", 1, 18)); // NOI18N
        jLabelTipoUsurario.setText("TIPO");
        jPanelLogin.add(jLabelTipoUsurario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 70, 30));

        jButtonIngresar.setBackground(new java.awt.Color(104, 137, 0));
        jButtonIngresar.setFont(new java.awt.Font("Roboto SemiCondensed Black", 0, 24)); // NOI18N
        jButtonIngresar.setText("INGRESAR");
        jButtonIngresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jButtonIngresar.setBorderPainted(false);
        jButtonIngresar.setContentAreaFilled(false);
        jButtonIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonIngresar.setFocusPainted(false);
        jButtonIngresar.setMaximumSize(new java.awt.Dimension(111, 31));
        jButtonIngresar.setMinimumSize(new java.awt.Dimension(111, 31));
        jButtonIngresar.setOpaque(true);
        jButtonIngresar.setPreferredSize(new java.awt.Dimension(111, 31));
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });
        jPanelLogin.add(jButtonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 170, 40));

        titulo.setFont(new java.awt.Font("Roboto SemiCondensed ExtraBold", 1, 24)); // NOI18N
        titulo.setText("Inicio de sesion");
        jPanelLogin.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 180, 30));

        jButtonRegistro.setBackground(new java.awt.Color(104, 137, 0));
        jButtonRegistro.setFont(new java.awt.Font("Roboto SemiCondensed Black", 0, 24)); // NOI18N
        jButtonRegistro.setText("REGISTRARSE");
        jButtonRegistro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jButtonRegistro.setBorderPainted(false);
        jButtonRegistro.setContentAreaFilled(false);
        jButtonRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegistro.setFocusPainted(false);
        jButtonRegistro.setMaximumSize(new java.awt.Dimension(111, 31));
        jButtonRegistro.setMinimumSize(new java.awt.Dimension(111, 31));
        jButtonRegistro.setOpaque(true);
        jButtonRegistro.setPreferredSize(new java.awt.Dimension(111, 31));
        jButtonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistroActionPerformed(evt);
            }
        });
        jPanelLogin.add(jButtonRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 170, 40));

        BackGround.add(jPanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 430, 370));

        jLabelFondo.setBackground(new java.awt.Color(0, 0, 0));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoLuzBlanca.png"))); // NOI18N
        jLabelFondo.setText("Fondo");
        jLabelFondo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelFondo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabelFondo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        BackGround.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-290, -580, 870, 1040));

        getContentPane().add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jComboBoxTipoUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoUActionPerformed
        // Aquí reaccionamos a la selección del usuario
        String tipoSeleccionado = jComboBoxTipoU.getSelectedItem().toString().toLowerCase();
        System.out.println("Seleccionaste: " + tipoSeleccionado);
    }//GEN-LAST:event_jComboBoxTipoUActionPerformed

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed

        // 
        String usuario = jTextFieldUsuario.getText();
        String contrasenia = new String(jPasswordFieldContraseña.getPassword());
        String tipo = jComboBoxTipoU.getSelectedItem().toString().toLowerCase();
        
        // instancia de clase usuarioDao
        UsuarioDAO daoUsuario = new UsuarioDAO();
        boolean accesoValido = daoUsuario.validarUsuario(usuario, contrasenia, tipo); //llamamos al metodo que nos devuelve si esta en la bd o no
        
        /*clase dos usuarioDao2
        UsuarioDao2 usu = new UsuarioDao2();
        boolean accesoValido = usu.validarUsuario(usuario, contrasenia, tipo); */
   
        // verificamos el acceso
        if(accesoValido){
            // abrimos la ventana del pomodoro
            VentanaPrincipal pomodoro = new VentanaPrincipal(); // instanciamos la ventana pomodoro
            pomodoro.setVisible(true);
            
            // si llega hasta aqui cerramos el login
            this.dispose();
            
        }else{
            JOptionPane.showMessageDialog(this, "Usuario, contraseña o tipo de usuario erroneo", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void jLabelSalirXMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirXMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelSalirXMousePressed

    private void jPasswordFieldContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldContraseñaActionPerformed

    private void jPasswordFieldContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseñaFocusGained
        // Quitamos los puntitos al entrar en el campo   
        jPasswordFieldContraseña.setText("");
        jPasswordFieldContraseña.setEchoChar((char)0);
    }//GEN-LAST:event_jPasswordFieldContraseñaFocusGained

    private void jPasswordFieldContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseñaFocusLost
        // Volvemos a poner los puntitos al salir
        
        // Si el campo queda vacío, puedes volver a poner un placeholder
        if (jPasswordFieldContraseña.getPassword().length == 0) {
            jPasswordFieldContraseña.setText("Introduce tu contraseña");
            jPasswordFieldContraseña.setEchoChar((char)0); // sin puntos para el placeholder
            } else {
            // Si el usuario escribió algo, vuelve a poner los puntitos
            jPasswordFieldContraseña.setEchoChar('•'); 
            }
    }//GEN-LAST:event_jPasswordFieldContraseñaFocusLost

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
 
        // Mover la ventana
        int desplazamientoX = evt.getXOnScreen() - mouseX;
        int desplazamientoY = evt.getYOnScreen() - mouseY;
        
        //mover la ventana a la nueva posicion
        this.setLocation(this.getX() + desplazamientoX, this.getY() + desplazamientoY);
        
        //Actualizar las posiciones bases del mouse
        mouseX = evt.getXOnScreen();
        mouseY = evt.getYOnScreen();    
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // evento que se usa para mover la pantalla         
        mouseX = evt.getXOnScreen();
        mouseY = evt.getYOnScreen();
        
    }//GEN-LAST:event_formMousePressed

    private void jButtonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistroActionPerformed
 
        // para el registro de un usuario 
        String usuario = jTextFieldUsuario.getText();
        String contrasenia = new String(jPasswordFieldContraseña.getPassword());
        String tipo = jComboBoxTipoU.getSelectedItem().toString().toLowerCase();
       
        
        UsuarioDAO dao = new UsuarioDAO();
        boolean registroCorrecto = dao.registrarUsuario(usuario, contrasenia, tipo); 
        
        /*UsuarioDao2 usu = new UsuarioDao2();
        boolean usuarioExi = usu.usuarioExiste(usuario, tipo); PRUEBA DE VARIAS TABLAS*/
        

        if (registroCorrecto) {
            JOptionPane.showMessageDialog(this, "Usuario registrado correctamente");
        } else {
            JOptionPane.showMessageDialog(this, "El usuario ya existe o hubo un error en el registro", 
                                          "Registro fallido", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonRegistroActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JButton jButtonRegistro;
    private javax.swing.JComboBox<String> jComboBoxTipoU;
    private javax.swing.JLabel jLabelContrasenia;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelSalirX;
    private javax.swing.JLabel jLabelTipoUsurario;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPanel jPanelSalir;
    private javax.swing.JPasswordField jPasswordFieldContraseña;
    private javax.swing.JTextField jTextFieldUsuario;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
