/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ventanaEmergente;

import java.awt.Color;

/**
 *
 * @author caroR
 */
public class MensajeTempo extends javax.swing.JDialog {

    /**
     * Creates new form mensajeV
     */
    public MensajeTempo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.setLocationRelativeTo(null); //centra la ventana en la pantalla
        
        //para poner en el panel Login semitrasparente
        jPanelMnsj.setBorder(new ui.RoundedBorder(20, new Color(200, 200, 200), 5));
        jPanelMnsj.setBackground(new java.awt.Color(255, 255, 255, 180)); // blanco semitransparente
        jPanelMnsj.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jPanelBotonOK = new javax.swing.JPanel();
        jLabelBtOK = new javax.swing.JLabel();
        jPanelMnsj = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Terminaste!");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(350, 350));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        jPanelBotonOK.setBackground(new java.awt.Color(0, 0, 0));
        jPanelBotonOK.setFocusable(false);
        jPanelBotonOK.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBtOK.setBackground(new java.awt.Color(0, 0, 0));
        jLabelBtOK.setFont(new java.awt.Font("Roboto SemiCondensed Black", 0, 36)); // NOI18N
        jLabelBtOK.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtOK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBtOK.setText("X");
        jLabelBtOK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabelBtOK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBtOK.setInheritsPopupMenu(false);
        jLabelBtOK.setOpaque(true);
        jLabelBtOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBtOKMouseClicked(evt);
            }
        });
        jPanelBotonOK.add(jLabelBtOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        getContentPane().add(jPanelBotonOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 40, 40));

        jPanelMnsj.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Roboto SemiCondensed Black", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BIEN HECHO!");
        jPanelMnsj.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 300, 110));

        jLabel1.setFont(new java.awt.Font("Roboto SemiCondensed Black", 0, 48)); // NOI18N
        jLabel1.setText("BIEN HECHO!");
        jPanelMnsj.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        getContentPane().add(jPanelMnsj, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 310, 130));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoSegundaVentana.png"))); // NOI18N
        fondo.setText("imagenFondo");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-360, -490, 1420, 1030));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelBtOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtOKMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabelBtOKMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MensajeTempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MensajeTempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MensajeTempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MensajeTempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MensajeTempo dialog = new MensajeTempo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBtOK;
    private javax.swing.JPanel jPanelBotonOK;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelMnsj;
    // End of variables declaration//GEN-END:variables
}
