/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ventanaEmergente;

import java.awt.Color;

/**
 *
 * @author caroR
 */
public class MensajeTareasCom extends javax.swing.JDialog {

    /**
     * Creates new form MensajeTareasCom
     */
    public MensajeTareasCom(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //para poner en el panel Login semitrasparente
        //jPanelMnsj.setBorder(new ui.RoundedBorder(20, new Color(200, 200, 200), 5));
        jPanelMnsj.setBackground(new java.awt.Color(255, 255, 255, 180)); // blanco semitransparente
        jPanelMnsj.setOpaque(true);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelOK = new javax.swing.JPanel();
        jLabelBOK = new javax.swing.JLabel();
        jPanelMnsj = new javax.swing.JPanel();
        Letrasnegras = new javax.swing.JLabel();
        letrasGris = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelOK.setBackground(new java.awt.Color(102, 137, 91));
        jPanelOK.setForeground(new java.awt.Color(102, 137, 91));
        jPanelOK.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBOK.setBackground(new java.awt.Color(0, 0, 0));
        jLabelBOK.setFont(new java.awt.Font("Roboto SemiCondensed Black", 0, 24)); // NOI18N
        jLabelBOK.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBOK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBOK.setText("OK");
        jLabelBOK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabelBOK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBOK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelBOK.setOpaque(true);
        jLabelBOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBOKMouseClicked(evt);
            }
        });
        jPanelOK.add(jLabelBOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel1.add(jPanelOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 50, 40));

        jPanelMnsj.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Letrasnegras.setFont(new java.awt.Font("Roboto SemiCondensed Black", 0, 36)); // NOI18N
        Letrasnegras.setText("Tareas NO completas por ahora");
        jPanelMnsj.add(Letrasnegras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 600, 60));

        letrasGris.setBackground(new java.awt.Color(255, 255, 255));
        letrasGris.setFont(new java.awt.Font("Roboto SemiCondensed Black", 0, 36)); // NOI18N
        letrasGris.setForeground(new java.awt.Color(153, 153, 153));
        letrasGris.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        letrasGris.setText("Tareas NO completas por ahora");
        jPanelMnsj.add(letrasGris, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 530, 110));

        jLabel2.setFont(new java.awt.Font("Roboto Condensed Black", 0, 23)); // NOI18N
        jLabel2.setText("Termina una con calma y abre espacio para la siguiente");
        jPanelMnsj.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 560, 50));

        jPanel1.add(jPanelMnsj, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 580, 180));

        jLabelFondo.setBackground(new java.awt.Color(102, 137, 91));
        jLabelFondo.setForeground(new java.awt.Color(102, 137, 91));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoSegundaVentana.png"))); // NOI18N
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -470, 700, 820));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 609, 323));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelBOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBOKMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabelBOKMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MensajeTareasCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MensajeTareasCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MensajeTareasCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MensajeTareasCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MensajeTareasCom dialog = new MensajeTareasCom(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Letrasnegras;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBOK;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMnsj;
    private javax.swing.JPanel jPanelOK;
    private javax.swing.JLabel letrasGris;
    // End of variables declaration//GEN-END:variables
}
